# Stage 1: Build Angular application
FROM node:18.10 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve Angular application with NGINX
FROM nginx:alpine
COPY --from=build /app/dist/interview /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
